import { defineType, defineField } from "sanity";

export const project = defineType({
  name: "project",
  title: "Project",
  type: "document",
  fields: [
    defineField({ name: "projectName", title: "Project Name", type: "string", validation: (r) => r.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "projectName" }, validation: (r) => r.required() }),
    defineField({ name: "projectCategory", title: "Project Category", type: "reference", to: [{ type: "projectCategory" }] }),
    defineField({ name: "client", title: "Client", type: "string" }),
    defineField({ name: "completedDate", title: "Completed Date", type: "string" }),
    defineField({ name: "size", title: "Size", type: "string" }),
    defineField({ name: "duration", title: "Duration", type: "string" }),
    defineField({ name: "featuredTitle", title: "Featured Title", type: "string" }),
    defineField({ name: "featuredImage1", title: "Featured Image 1", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "featuredImage2", title: "Featured Image 2", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "galleryImage1", title: "Gallery Image 1", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "galleryImage2", title: "Gallery Image 2", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "galleryImage3", title: "Gallery Image 3", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "galleryImage4", title: "Gallery Image 4", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "galleryImage5", title: "Gallery Image 5", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "galleryImage6", title: "Gallery Image 6", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "galleryImage7", title: "Gallery Image 7", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "galleryImage8", title: "Gallery Image 8", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "galleryImage9", title: "Gallery Image 9", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "galleryImage10", title: "Gallery Image 10", type: "image", fields: [defineField({ name: "alt", title: "Alt Text", type: "string" })] }),
    defineField({ name: "sectionEyebrow1", title: "Section Eyebrow 1", type: "string" }),
    defineField({ name: "sectionHeading1", title: "Section Heading 1", type: "string" }),
    defineField({ name: "tableHeader1", title: "Table Header 1", type: "string" }),
    defineField({ name: "tableColumnStat1A", title: "Table Column Stat 1A", type: "string" }),
    defineField({ name: "tableColumnStat1B", title: "Table Column Stat 1B", type: "string" }),
    defineField({ name: "tableColumnStat1C", title: "Table Column Stat 1C", type: "string" }),
    defineField({ name: "tableHeader2", title: "Table Header 2", type: "string" }),
    defineField({ name: "tableColumnStat2A", title: "Table Column Stat 2A", type: "string" }),
    defineField({ name: "tableColumnStat2B", title: "Table Column Stat 2B", type: "string" }),
    defineField({ name: "tableColumnStat2C", title: "Table Column Stat 2C", type: "string" }),
    defineField({ name: "tableHeader3", title: "Table Header 3", type: "string" }),
    defineField({ name: "tableColumnStat3A", title: "Table Column Stat 3A", type: "string" }),
    defineField({ name: "tableColumnStat3B", title: "Table Column Stat 3B", type: "string" }),
    defineField({ name: "tableColumnStat3C", title: "Table Column Stat 3C", type: "string" }),
    defineField({ name: "sectionEyebrow2", title: "Section Eyebrow 2", type: "string" }),
    defineField({ name: "sectionHeading2", title: "Section Heading 2", type: "string" }),
    defineField({ name: "sectionParagraph2", title: "Section Paragraph 2", type: "text" }),
    defineField({ name: "sectionEyebrow3", title: "Section Eyebrow 3", type: "string" }),
    defineField({ name: "sectionHeading3", title: "Section Heading 3", type: "string" }),
    defineField({ name: "sectionParagraph3", title: "Section Paragraph 3", type: "text" }),
    defineField({ name: "sectionEyebrow4", title: "Section Eyebrow 4", type: "string" }),
    defineField({ name: "sectionHeading4", title: "Section Heading 4", type: "string" }),
    defineField({ name: "sectionParagraph4", title: "Section Paragraph 4", type: "text" }),
    defineField({ name: "seoTitle", title: "SEO Title", type: "string" }),
    defineField({ name: "seoDescription", title: "SEO Description", type: "text" }),
    defineField({ name: "seoImage", title: "SEO Image", type: "image" }),
  ],
  preview: {
    select: { title: 'projectName', subtitle: 'client' },
    prepare: (selection) => ({ title: selection.title, subtitle: selection.subtitle }),
  },
});
